### PR TITLE
Runtime - Support frozen intrinsics

### LINKED ISSUE #410: runtime - class inheritance pattern not compatible with frozen intrinsics
it is becoming increasingly common to freeze javascript intrinsics (Object, Array...) (see [nodejs](https://nodejs.org/api/cli.html#cli_frozen_intrinsics), [endo/ses](https://github.com/endojs/endo/tree/master/packages/ses), [xs](https://blog.moddable.com/blog/secureprivate/))

while this is generally not an issue for packages that do not extend intrinsics, there are a few unfortunate side effects due to javascript's ["override mistake"](https://github.com/tc39/ecma262/pull/1307), namely `obj.constructor = ...` fails due to the inherited property "constructor" being read-only on `Object.prototype`

here is the inheritance pattern at fault
https://github.com/facebook/regenerator/blob/0c2aba1af78be03da05de96b6c69f231b85993dc/packages/regenerator-runtime/runtime.js#L105-L106

here is a compatible inheritance pattern
https://github.com/isaacs/inherits/blob/9a2c29400c6d491e0b7beefe0c32efa3b462545d/inherits_browser.js#L6-L13
alternatively you can just use defineProperty instead of assignment

reproduction steps:
```js
Object.freeze(Object.prototype)
require('./runtime.js')
```

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #410 

thanks for taking the time to review this change :heart: 
I wasn't sure exactly what platform to target with the tests, feedback welcome

these seemed like the least invasive change to make this work
I tested this locally against a more significant freezing of the intrinsics, built from nodejs internal [freeze_intrinsics](https://github.com/nodejs/node/blob/7c808170f5bf27b2d4a83ae5934b5e231bb5c1bc/lib/internal/freeze_intrinsics.js) and [primordials](https://github.com/nodejs/node/blob/7c808170f5bf27b2d4a83ae5934b5e231bb5c1bc/lib/internal/per_context/primordials.js)
here is a draft PR that includes those additional test utilities https://github.com/facebook/regenerator/pull/412
those tests pass with no additional change to the runtime

### CODE REVIEW

**Comment by kumavis** [comment]
cla signed

**Comment by kumavis** [comment]
this needs an additional fix for this part 
```js
  Gp[iteratorSymbol] = function() {
    return this;
  };
  ```

**Comment by kumavis** [comment]
cc @kriskowal @ljharb noticed both of you in the commits and that you're familiar with the override mistake issue

File: packages/regenerator-runtime/runtime.js [hunk 1]
```diff
@@ -102,8 +102,9 @@ var runtime = (function (exports) {
 
   var Gp = GeneratorFunctionPrototype.prototype =
     Generator.prototype = Object.create(IteratorPrototype);
```
Comment (ljharb) [inline packages/regenerator-runtime/runtime.js:104]: wouldn't this line also perhaps trigger the same issue, since `.prototype` is also locked down?

**Review by ljharb — COMMENTED** [review]
LGTM overall

File: packages/regenerator-runtime/runtime.js (hunk 1 above)
Comment (kumavis) [reply packages/regenerator-runtime/runtime.js:104]: I believe this is covered by the added tests. function-syntax classes have their own writable `prototype` property, so it is not affected by the override mistake
```js
function Animal () {}
Reflect.getOwnPropertyDescriptor(Animal, 'prototype')
//=> Object { value: {…}, writable: true, enumerable: false, configurable: false }
```

File: test/run.js [hunk 2]
```diff
@@ -141,6 +141,12 @@ if (semver.gte(process.version, "4.0.0")) {
   ]);
 }
 
+enqueue("mocha", [
+  "--harmony",
+  "--reporter", "spec",
+  "./test/frozen-intrinsics.js",
+]);
```
Comment (benjamn) [inline test/run.js:148]: @kumavis Nice, this `enqeue` will run the tests you added in an isolated child process, so the `Object.freeze` stuff doesn't leak into other tests.

**Review by benjamn — APPROVED** [review]
LGTM2. Thanks for tackling this @kumavis and for the supporting review @ljharb!

**Comment by benjamn** [comment]
@kumavis @ljharb Just published this to npm in `regenerator-runtime@0.13.8`. However (out of an abundance of caution for a package with this many users), I used the `next` tag instead of `latest` for now. Let me know if/when you think we can promote it to `latest`. Thanks!
